# create:
# conda env create --file environment.yml
# update:
# conda env update --file environment.yml --prune
name: manflow

channels:
  - conda-forge
  - pytorch

dependencies:
  - autoflake
  - black
  - cudatoolkit
  - flake8
  - isort
  - jupyter
  - pandas
  - seaborn
  - sympytorch
  - matplotlib
  - numpy
  - parameterized
  - scikit-learn
  - scikit-image
  - ninja
  - pip
  - pip:
    - torchtestcase
    - -e .  # install package in development mode
    - umnn
    - normflows
    - sympytorch
    - gpytorch
  - pytest
  - python
  - pytorch
  - pyyaml
  - tensorboard
  - tqdm

# Additionally, install the provided version of FlowConductor
# repository of the original version: https://github.com/FabricioArendTorres/FlowConductor
# use a local pip install. in the folder of the provided FlowConductor package with the 'manflow' environment active
# -> execute the command: pip install -e .
